config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    get 'pdf'
    post 'pdf_raport'
  end
  resources :item_groups
  resources :item_types
  resources :items do
    get 'service'
    post 'add_history'
  end

  # custom routes
  get 'item_barcodes' => 'items#index_barcodes'
  get 'ajax' => 'items#ajax'
  get 'change_status' => 'items#change_status'
  get 'panel' => 'home#scan'
  get 'schedule' => 'home#schedule_pdf'
  get 'orders_panel' => 'orders#panel'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/controllers/item_types_controller.rb
class ItemTypesController < ApplicationController
  before_action :set_item_type, only: [:show, :edit, :update, :destroy]

  # GET /item_types
  def index
    @item_types = ItemType.all
  end

  # GET /item_types/1
  def show
  end

  # GET /item_types/new
  def new
    @item_type = ItemType.new
  end

  # GET /item_types/1/edit
  def edit
  end

  # POST /item_types
  def create
    @item_type = ItemType.new(item_type_params)

    if @item_type.save
      redirect_to item_types_path, notice: 'Typ został stworzony.'
    else
      render :new
    end
  end

  # PATCH/PUT /item_types/1
  def update
    if @item_type.update(item_type_params)
      redirect_to item_types_path, notice: 'Typ został zapisany.'
    else
      render :edit
    end
  end

  # DELETE /item_types/1
  def destroy
    @item_type.destroy
    redirect_to item_types_url, notice: 'Typ został usunięty.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_type
      @item_type = ItemType.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_type_params
      params.require(:item_type).permit(:name, :icon, :feature_keys)
    end
end

app/views/item_types/_form.html.erb
<%= bootstrap_form_for(@item_type) do |f| %>

  <%= f.text_field :name, label: 'Nazwa' %>

  <p>
    <label>Dodatkowe atrybuty grupy</label>
    <%= f.text_field :feature_keys, label: nil, hide_label: true, 'data-role'=>'tagsinput' %>
  </p>

  <%= f.form_group :icon, label: {text: 'Ikona'}, help: nil do %>

    <br />
    <div class="row">
      <% item_type_icons.each do |it| %>
        <div class="col-md-1">
          <%= f.radio_button :icon, it, label: ('<i class="' + it + ' fa-lg" aria-hidden="true"></i>').html_safe, inline: true %>
        </div>
      <% end %>
    </div>  
  <% end %>

  <div class="actions">
    <%= f.submit 'Zapisz', class: 'btn btn-success' %>
    <%= link_to 'Wróć', items_path, class: 'btn btn-default' %>
    <%= link_to 'Usuń typ', item_type, class: 'btn btn-danger', method: :delete, data: { confirm: 'Na pewno chcesz usunąć typ? Wszystkie powiązane z typ typem przedmioty zostaną także usunięte. Operacja ta jest nie odwracalna.' } if !@item_type.new_record?%>
  </div>

<% end %>

app/views/item_types/edit.html.erb
<div class="page-inner">
  <div class="page-title">
    <h3 class="breadcrumb-header">Edytuj typ sprzętu</h3>
  </div>
  <div id="main-wrapper">
    <div class="row">
      <div class="col-lg-12">
        <%= render 'form', item_type: @item_type %>
      </div>
    </div>
  </div>
</div>

app/views/item_types/index.html.erb
<style>
.btn-light { border: 1px gray solid; }
</style>

<div class="page-inner">
  <div class="page-title">
      <h3 class="breadcrumb-header">Typy sprzętu</h3>
      <%= link_to '<i class="fa fa-plus"></i> Dodaj typ'.html_safe, new_item_type_path, class: 'btn btn-info'  %>
  </div>
  <div id="main-wrapper">
    <div class="row">
      <div class="col-lg-12"><br>

        <% @item_types.each do |item_type| %>
          <span> 
            
            <%= link_to edit_item_type_path(item_type), class: 'btn btn-light btn-rounded' do %>
              <i class="<%= item_type.icon %> fa-fw" aria-hidden="true"></i>
              <%= item_type.name %>
            <% end %>
          </span>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/item_types/new.html.erb
<div class="page-inner">
  <div class="page-title">
    <h3 class="breadcrumb-header">Dodaj typ sprzętu</h3>
  </div>
  <div id="main-wrapper">
    <div class="row">
      <div class="col-lg-12">
        <%= render 'form', item_type: @item_type %>
      </div>
    </div>
  </div>
</div>

app/views/item_types/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_item_type_path(@item_type) %> |
<%= link_to 'Back', item_types_path, class: 'btn btn-light' %>