config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    get 'pdf'
    post 'pdf_raport'
  end
  resources :item_groups
  resources :item_types
  resources :items do
    get 'service'
    post 'add_history'
  end

  # custom routes
  get 'item_barcodes' => 'items#index_barcodes'
  get 'ajax' => 'items#ajax'
  get 'change_status' => 'items#change_status'
  get 'panel' => 'home#scan'
  get 'schedule' => 'home#schedule_pdf'
  get 'orders_panel' => 'orders#panel'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/order.rb
class Order < ApplicationRecord

  has_and_belongs_to_many :items, through: :orders_items
  after_create :set_item_statuses_to_reserved

  def set_item_statuses_to_reserved
    items.each do |item|
      item.update(status: ITEM_RESERVED)
    end
    end

  def barcode
    require 'barby/barcode/code_128'
    require 'barby/outputter/cairo_outputter'

    begin
      barcode = Barby::Code128.new(number.rjust(8, '0'))
      outputter = Barby::CairoOutputter.new(barcode)
      outputter.to_svg(height: 35, ydim: 18, margin: 0)
    rescue
      "<span>---</span>"
    end
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  def index
    if params[:all]
      @orders = Order.includes(:items => :item_type).where(status: [ORDER_CREATED, ORDER_WAITING]).where.not(id: 1)
    else
      @orders = Order.includes(:items => :item_type).where(status: ORDER_CREATED).where.not(id: 1)
    end
  end

  # GET /orders/1
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @conflict_orders = {}
  end

  # GET /orders/1/edit
  def edit
  end

  def panel
    if params[:order] && params[:order][:number]
      order = Order.where(number: params[:order][:number]).first
      back_param = params[:order][:back] rescue nil
      redirect_to order_path(order, back: back_param) and return if order
    end
    if params[:back]
      @orders = Order.includes(:items => :item_type).where(status: ORDER_WAITING).where.not(id: 1) + Order.includes(:items => :item_type).where(status: ORDER_CREATED).where(items: {status: [ITEM_BUSY, ITEM_SERVICE]}).where.not(id: 1)
    else
      @orders = Order.includes(:items => :item_type).where(status: ORDER_CREATED).where.not(id: 1) 
    end
  end

  def pdf
    @order = Order.find(params[:order_id])
    render pdf: ["Zlecenie", @order.name, @order.number].join('-'), encoding: 'utf8'   # Excluding ".pdf" extension.
  end

  def pdf_raport
    @order = Order.find(params[:order_id])
    @items = Item.where(ean: params[:order][:number].split(','))
    
    @order.owner = params[:order][:owner] if params[:order][:owner]
    @order.description = params[:order][:description] if params[:order][:description]
    back_param = !params[:order][:back].empty? rescue false

    if back_param && @items.pluck(:ean) & @order.items.where(status: [ITEM_BUSY, ITEM_SERVICE]).pluck(:ean) == @order.items.where(status: [ITEM_BUSY, ITEM_SERVICE]).pluck(:ean)
      @order.status = ORDER_DONE
    elsif !back_param && @items.pluck(:ean) & @order.items.where(status: ITEM_RESERVED).pluck(:ean) == @order.items.where(status: ITEM_RESERVED).pluck(:ean)
      @order.status = ORDER_WAITING
    end

    if @order.save && !back_param
      @items.each do |i| 
        if @order && !@order.items.include?(i)
          @order.items.push(i)
        end
        i.update(status: ITEM_BUSY, owner: @order.owner)
      end
      render pdf: ["Raport", @order.name, @order.number].join('-'), encoding: 'utf8'   # Excluding ".pdf" extension.
    elsif back_param
      @items.each{|i| i.update(status: ITEM_ACTIVE, owner: '')}
      redirect_to orders_path, notice: "Sprzęt został zdany."
    else
      redirect_to @order, notice: 'Coś poszło nie tak'
    end

  end

  # POST /orders
  def create
    @order = Order.new(description: order_params[:description],
                       number: order_params[:number],
                       owner: order_params[:owner],
                       manager: order_params[:manager],
                       name: order_params[:name],
                       date_from: Time.parse(order_params[:date_from]),
                       date_to: Time.parse(order_params[:date_to])
                      )
    order_items = []
    Item.where(id: order_params[:item_ids]).each { |item| order_items << item }
    ItemGroup.where(id: order_params[:group_ids]).each do |group|
      group.items.each { |item| order_items << item }
    end

    @conflict_orders = {}
    order_items.uniq.each do |item|
      item.orders.each do |item_order|
        if dates_conflict?(@order, item_order)
          @conflict_orders[item_order.name] = {order: item_order, items: []} if @conflict_orders[item_order.name].nil?
          @conflict_orders[item_order.name][:items] << item
          break
        end
      end
      @order.items.push(item)
    end
    
    unless @conflict_orders.empty?
      render :new and return
    end
    # if not all items have status of STATUS_ACTIVE
    if order_items.map { |i| i.status }.uniq.include?(ITEM_SERVICE)
      redirect_to orders_path, alert: 'Błąd. Niektóre przedmioty są w serwisie.' and return
    end

    if @order.save
      redirect_to orders_path, notice: 'Zlecenie zostało stworzone.'
    else
      render :new
    end
  end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
      redirect_to @order, notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /orders/1
  def destroy
    @order.destroy
    redirect_to orders_url, notice: 'Order was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def order_params
    params.require(:order).permit(:date_from, :date_to, :number, :owner, :manager, :name, :description, :item_ids => [], :group_ids => [])
  end

  def dates_conflict? o1, o2
    if (o2.date_from <= o1.date_to && o1.date_to <= o2.date_to) || 
       (o2.date_from <= o1.date_from && o1.date_from <= o2.date_to) ||
       (o1.date_from <= o2.date_to && o2.date_to <= o1.date_to) || 
       (o1.date_from <= o2.date_from && o2.date_from <= o1.date_to)
      true
    else
      false
    end
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= bootstrap_form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% @order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">

    <div class="col-md-6">
      <%= f.text_field :name, label: 'Nazwa' %>
    </div>

    <div class="col-md-6">
      <%= f.text_field :number, label: 'Numer' %>
    </div>

  </div>
  <div class="row">

    <div class="col-md-6">
      <%= f.text_field :owner, label: 'Wypożyczający' %>
    </div>

    <div class="col-md-6">
      <%= f.text_field :manager, label: 'Kierownik produkcji' %>
    </div>

  </div>

  <div class="row">

    <div class="col-md-6">

      <div class="form-group">
        <label>Data od</label>
        <div class='input-group date' id='datetimepicker1'>
          <input type='text' name="order[date_from]" class="form-control" value="<%= params[:order][:date_from] rescue "" %>" />
          <span class="input-group-addon">
              <i class="fa fa-calendar" aria-hidden="true"></i>
          </span>
        </div>
      </div>

    </div>

    <div class="col-md-6">

      <div class="form-group">
        <label>Data do</label>
        <div class='input-group date' id='datetimepicker2'>
          <input type='text' name="order[date_to]" class="form-control" value="<%= params[:order][:date_to] rescue "" %>" />
          <span class="input-group-addon">
              <i class="fa fa-calendar" aria-hidden="true"></i>
          </span>
        </div>
      </div>

    </div>
  </div>


  <%= f.text_area :description, label: 'Uwagi' %>

  <%= f.select :item_ids, Item.where(status: ITEM_SERVICE).collect {|x| ["#{x.name} (#{x.ean})", x.id]}, { label: 'Sprzęt'}, :multiple => true, :data => {:placeholder => "Wybierz..."}, class: 'chosen-select' %>
  <%= f.select :group_ids, (ItemGroup.all - ItemGroup.includes(:items).where(items: {status: [ITEM_SERVICE]})).collect {|x| [x.name, x.id]}, { label: 'Grupy'}, :multiple => true, :data => {:placeholder => "Wybierz..."}, class: 'chosen-select' %>

  <% if @conflict_orders.empty? %>
    <p class="text-muted">Upewnij się, że wybrany sprzęt nie koliduje terminami z innym zleceniem!</p>
  <% else %>
    <p class="text-danger">Wybrany sprzęt koliduje z następującymi zleceniami: </p>
    <% @conflict_orders.each do |(o, v)| %>
      <p class="text-danger"><%= o %> (<%= v[:order].date_from.strftime("%d-%m-%Y %H:%M") %> do <%= v[:order].date_from.strftime("%d-%m-%Y %H:%M") %>):<br>
        <% v[:items].each do |i| %>
          - <%= i.name %> (<%= i.item_group.name %>)<br>
        <% end %>
      </p>
    <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit 'Zapisz', class: 'btn btn-success' %>
    <%= link_to 'Wróć', items_path, class: 'btn btn-default' %>
  </div>
<% end %>
<script>
    $(document).ready(function(){
        $('.chosen-select').chosen();
    });
        $(function () {
            $('#datetimepicker1').datetimepicker();
            $('#datetimepicker2').datetimepicker();
        });

</script>

app/views/orders/edit.html.erb
;_;

app/views/orders/index.html.erb
<div class="page-inner">
  <div class="page-title">
    <h3 class="breadcrumb-header">Zlecenia</h3>
    <%= link_to '<i class="fa fa-plus"></i> Dodaj zlecenie'.html_safe, new_order_path, class: 'btn btn-info' %>
  </div>
  <div id="main-wrapper">
    <div class="row">
      <div class="col-lg-12">

        <br>
        <div class="form-group">
          <label for="item_name">Nazwa</label>
          <input class="form-control" type="text" onkeyup="filterInput()" placeholder="Filtruj.." id="filter-input">
        </div>
        <table class='responsive table table-sm' id='dttb-items'>
          <thead>
          <tr>
            <th>Nazwa</th>
            <th>Numer</th>
            <th>Wypożyczający</th>
            <th>Kierownik produkcji</th>
            <th>Data od</th>
            <th>Data do</th>
            <th>Uwagi</th>
            <th>Operacje</th>
            <th>Status</th>
          </tr>
          </thead>

          <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td>
                <%= link_to order do %>
                  <%= order.name %>
                <% end %>
              </td>
              <td>
                <%= order.number.rjust(8, '0') %>
              </td>
              <td>
                <%= order.owner %>
              </td>
              <td>
                <%= order.manager %>
              </td>
              <td>
                <%= order.date_from.strftime("%d-%m-%Y %H:%M") %>
              </td>
              <td>
                <%= order.date_to.strftime("%d-%m-%Y %H:%M") %>
              </td>
              <td>
                <%= order.description %>
              </td>
              <td>
                <%= link_to 'Generuj PDF', order_pdf_path(order), target: "_blank", class: 'btn btn-primary btn-xs' %>
              </td>
              <td>
                <% case order.status %>
                <% when 0 %>
                  <%= link_to order, class: 'btn btn-success btn-xs' do %>
                    Wydaj sprzęt
                  <% end %>
                <% when 1 %>
                  <span class="label label-success"><i class="fa fa-fw fa-check" aria-hidden="true"></i> Wydany</span>
                <% else %>
                  -
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

    function filterInput() {
        // Declare variables
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("filter-input");
        filter = input.value.toUpperCase();
        table = document.getElementById("dttb-items");
        tr = table.getElementsByTagName("tr");

        // Loop through all table rows, and hide those who don't match the search query
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            td2 = tr[i].getElementsByTagName("td")[1];
            td3 = tr[i].getElementsByTagName("td")[2];
            td4 = tr[i].getElementsByTagName("td")[3];
            td5 = tr[i].getElementsByTagName("td")[4];
            td6 = tr[i].getElementsByTagName("td")[5];
            td7 = tr[i].getElementsByTagName("td")[6];
            td8 = tr[i].getElementsByTagName("td")[7];
            if (td) {
                txtValue = td.textContent || td.innerText;
                txtValue2 = td2.textContent || td2.innerText;
                txtValue3 = td3.textContent || td3.innerText;
                txtValue4 = td4.textContent || td4.innerText;
                txtValue5 = td5.textContent || td5.innerText;
                txtValue6 = td6.textContent || td6.innerText;
                txtValue7 = td7.textContent || td7.innerText;
                txtValue8 = td8.textContent || td8.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1 ||
                    txtValue2.toUpperCase().indexOf(filter) > -1 ||
                    txtValue3.toUpperCase().indexOf(filter) > -1 ||
                    txtValue4.toUpperCase().indexOf(filter) > -1 ||
                    txtValue5.toUpperCase().indexOf(filter) > -1 ||
                    txtValue6.toUpperCase().indexOf(filter) > -1 ||
                    txtValue7.toUpperCase().indexOf(filter) > -1 ||
                    txtValue8.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

</script>

app/views/orders/new.html.erb
<div class="page-inner">
  <div class="page-title">
    <h3 class="breadcrumb-header">Dodaj Zlecenie</h3>
  </div>
  <div id="main-wrapper">
    <div class="row">
      <div class="col-lg-12">
        <%= render 'form', order: @order %>
      </div>
    </div>
  </div>
</div>

app/views/orders/panel.html.erb
<div class="page-inner">
  <div class="page-title">
    <h3 class="breadcrumb-header">Zlecenia</h3> 
    <% if params[:back] %>
      <%= link_to 'Zdaj sprzęt bez zlecenia', order_path(1, back: true), class: 'btn btn-info' %>
    <% end %>
  </div>
  <div id="main-wrapper">
    <div class="row">
      <div class="col-lg-12">

        <br>
        <div class="form-group">
          <label for="item_name">Nazwa</label>
          <%= form_for Order.new, url: orders_panel_path, method: :get do |f| %>
            <input class="form-control" type="text" name="order[number]" onkeyup="filterInput()" placeholder="Filtruj.." id="filter-input">
            <% if params[:back] %>
              <input type="hidden" name="order[back]" value="<%=params[:back]%>">
            <% end %>
          <% end %>
        </div>
        <table class='responsive table table-sm' id='dttb-items'>
          <thead>
          <tr>
            <th>Nazwa</th>
            <th>Numer</th>
            <th>Wypożyczający</th>
            <th>Kierownik produkcji</th>
            <th>Data od</th>
            <th>Data do</th>
            <th>Uwagi</th>
            <th>Operacje</th>
            <th>Status</th>
          </tr>
          </thead>

          <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td>
                <%= link_to order_path(order, back: params[:back]) do %>
                  <%= order.name %>
                <% end %>
              </td>
              <td>
                <%= order.number.rjust(8, '0') %>
              </td>
              <td>
                <%= order.owner %>
              </td>
              <td>
                <%= order.manager %>
              </td>
              <td>
                <%= order.date_from.strftime("%d-%m-%Y %H:%M") %>
              </td>
              <td>
                <%= order.date_to.strftime("%d-%m-%Y %H:%M") %>
              </td>
              <td>
                <div class="truncate">
                  <%= order.description %>
                </div>
              </td>
              <td>
                <%= link_to 'Generuj PDF', order_pdf_path(order), class: 'btn btn-primary btn-xs' %>
              </td>
              <td>
                <% case order.status %>
                <% when 0 %>
                  <%= link_to order, class: 'btn btn-success btn-xs' do %>
                    Wydaj sprzęt
                  <% end %>
                <% when 1 %>
                  <span class="label label-success"><i class="fa fa-fw fa-check" aria-hidden="true"></i> Wydany</span>
                <% else %>
                  -
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

  // fucus input even if lost
  setTimeout(function () {
      $('input:text')[0].focus();
      $('#filter-input').on('focusout', function () {
          $('input:text')[0].focus();
      })
  }, 500);

  function filterInput() {
      // Declare variables
      var input, filter, table, tr, td, i, txtValue;
      input = document.getElementById("filter-input");
      filter = input.value.toUpperCase();
      table = document.getElementById("dttb-items");
      tr = table.getElementsByTagName("tr");

      // Loop through all table rows, and hide those who don't match the search query
      for (i = 0; i < tr.length; i++) {
          td = tr[i].getElementsByTagName("td")[0];
          td2 = tr[i].getElementsByTagName("td")[1];
          td3 = tr[i].getElementsByTagName("td")[2];
          td4 = tr[i].getElementsByTagName("td")[3];
          td5 = tr[i].getElementsByTagName("td")[4];
          td6 = tr[i].getElementsByTagName("td")[5];
          td7 = tr[i].getElementsByTagName("td")[6];
          td8 = tr[i].getElementsByTagName("td")[7];
          if (td) {
              txtValue = td.textContent || td.innerText;
              txtValue2 = td2.textContent || td2.innerText;
              txtValue3 = td3.textContent || td3.innerText;
              txtValue4 = td4.textContent || td4.innerText;
              txtValue5 = td5.textContent || td5.innerText;
              txtValue6 = td6.textContent || td6.innerText;
              txtValue7 = td7.textContent || td7.innerText;
              txtValue8 = td8.textContent || td8.innerText;
              if (txtValue.toUpperCase().indexOf(filter) > -1 ||
                  txtValue2.toUpperCase().indexOf(filter) > -1 ||
                  txtValue3.toUpperCase().indexOf(filter) > -1 ||
                  txtValue4.toUpperCase().indexOf(filter) > -1 ||
                  txtValue5.toUpperCase().indexOf(filter) > -1 ||
                  txtValue6.toUpperCase().indexOf(filter) > -1 ||
                  txtValue7.toUpperCase().indexOf(filter) > -1 ||
                  txtValue8.toUpperCase().indexOf(filter) > -1) {
                  tr[i].style.display = "";
              } else {
                  tr[i].style.display = "none";
              }
          }
      }
  }



</script>

app/views/orders/show.html.erb
<style>
  .order-table {table-layout: auto;}
  table tr td {
    padding: 5px;
  }
    table tr th {
    padding: 5px;
    font-weight: 800;
  }

  .item {
    margin: 2px;
  }

  .item-inactive {
    color: #dcdcdc
  }
  .card-back{
    display: none;
  }
</style>


<div class="page-inner">
  <div class="page-title">
    <h3 class="breadcrumb-header"><%= params[:back] ? 'Zdaj sprzęt' : 'Wydaj sprzęt' %></h3>
  </div>
  <div id="main-wrapper">
    <div class="row">
      <div class="col-lg-12">
        <div style="float: left; max-width: 600px;">
          <%= bootstrap_form_for(@order, url: order_pdf_raport_path(@order), method: :post) do |f| %>
            <div id="focus-id">
              <label>Zeskanuj sprzęt</label>
              <%= f.text_field :number, value: "", label: nil, hide_label: true, 'data-role' => 'tagsinput', width: 300 %>
              <input type="hidden" name="order[back]" value="<%= params[:back] %>">
            </div>

            <!-- Modal -->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Szczegóły zlecenia</h4>
                  </div>
                  <div class="modal-body">
                    <%= f.text_field :owner, label: 'Osoba' %>
                    <%= f.text_area :description, label: 'Opis' %>
                  </div>
                  <div class="modal-footer">
                    <%= f.submit "Dalej", class: "btn btn-success", :formtarget => "_blank", id: 'submit-form' %>
                  </div>
                </div>
              </div>
            </div>
            <% if @order.id == 1 %>
              <%= f.submit "Zdaj zeskanowany sprzęts", class: "btn btn-success btn-lg" %>
            <% end %>
          <% end %>
          <% if @order.id != 1 %>
          <button data-toggle="modal" data-target="#myModal" class="btn btn-success btn-lg btn-counter"><%= params[:back] ? 'Zdaj zeskanowany sprzęt' : 'Wydaj zeskanowany sprzęt' %></button>
          <% end %>

        </div>
        <% if @order.id != 1 %>
          <div style="float: left; margin-left: 150px;">
            <h5>Szczegóły zlecenia:</h5>
            <table class="order-table">
              <tr>
                <th style="text-align: right;"">Nazwa:</th>
                <td><%= @order.name %></td>
                <th style="text-align: right;">Numer:</th>
                <td><%= @order.number %></td>
              </tr>
              <tr>
                <th style="text-align: right;">Wypożyczający:</th>
                <td><%= @order.owner %></td>
                <th style="text-align: right;">Data od:</th>
                <td><%= @order.date_from.strftime("%d-%m-%Y %H:%M") %></td>
              </tr>
              <tr>
                <th style="text-align: right;">Kierownik Produkcji:</th>
                <td><%= @order.manager %></td>
                <th style="text-align: right;">Data do:</th>
                <td><%= @order.date_to.strftime("%d-%m-%Y %H:%M") %></td>
              </tr>
            </table>
          </div>
        <% end %>
      </div>
    </div>
    <br>
    <div class="row">
      <% if @order.id != 1 %>
      <div class="col-md-12">
        <div class="panel panel-white">
          <div class='panel-heading'>
            <h4 class='panel-title'>Sprzęt do <%= params[:back] ? 'zdania' : 'wydania' %></h4>
            <% if !params[:back] && (@order.items.pluck(:status).uniq & [ITEM_BUSY, ITEM_SERVICE]).count > 0 %>
              <div class="alert alert-danger" role="alert"><b>Uwaga!</b> Nie wszystkie przedmioty są dostępne.</div>
            <% end %>
          </div>
          <div class="panel-body">
            <div class="row items">
              <table class='responsive table table-sm'>
                <% @order.items.each do |item| %>
                  <% next if params[:back] && ![ITEM_BUSY, ITEM_SERVICE].include?(item.status) %>
                  <tr>
                    <td>
                      <%= link_to item.name, item, style: "color: inherit" %>
                    </td>
                    <td>
                      <%= link_to item, style: "color: inherit" do %>
                        <%= item.ean %>
                      <% end %>
                    </td>
                    <td>
                      <% if item.item_type %>
                        <%= item.item_type.fa %>
                        <%= item.item_type.name %>
                      <% end %>
                    </td>
                    <td>
                      <% if item.item_group %>
                        <%= link_to item.item_group.name, item.item_group, style: "color: inherit" %>
                      <% else %>
                        (brak)
                      <% end %>
                    </td>
                    <td class="col-md-2">
                      <div>
                        <% if (params[:back] && [ITEM_ACTIVE, ITEM_RESERVED].include?(item.status)) || (!params[:back] && [ITEM_BUSY, ITEM_SERVICE].include?(item.status))%>
                          <% case item.status %>
                        <% when ITEM_ACTIVE %>
                            <span class="label label-default"><i class="fa fa-fw fa-check" aria-hidden="true"></i> Na stanie</span>
                          <% when ITEM_RESERVED %>
                            <span class="label label-default"><i class="fa fa-fw fa-exclamation-triangle" aria-hidden="true"></i> Rezerwacja</span>
                          <% when ITEM_BUSY %>
                            <span class="label label-default"><i class="fa fa-circle-o-notch fa-spin fa-fw"></i> Zajęty</span>
                          <% when ITEM_SERVICE %>
                            <span class="label label-danger"><i class="fa fa-fw fa-times" aria-hidden="true"></i> Serwis</span>
                          <% else %>
                            -
                          <% end %>
                        <% else %>
                          <div class='card <%= item.ean %>-back card-back'>
                            <span class="label label-success"><i class="fa fa-fw fa-check" aria-hidden="true"></i>
                              <%= params[:back] ? 'Zdany' : 'Wydany' %>
                            </span>&nbsp;
                            <%= link_to item_service_path(item), remote: true, class: 'btn btn-danger btn-xs' do %>
                              <i class="fa fa-fw fa-wrench"></i>
                              Serwisuj
                            <% end %>
                          </div>
                          <div class='card <%= item.ean %>-front card-front'>
                            <span class="label label-info"><i class="fa fa-barcode fa-fw"></i> Zeskanuj</span>
                          </div>
                        <% end %>
                      </div>
                    </td>
                  </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <div class="col-md-12">
        <div class="panel panel-white">
          <div class='panel-heading'>
            <h4 class='panel-title'>Sprzęt <%= params[:back] ? 'zdany' : 'wydany' %> dodatkowo</h4>
          </div>
          <div class="panel-body">
            <table class="responsive table table-sm">
              <tbody class="items-container">
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>

  // fucus input even if lost
  setTimeout(function () {
    $('input:text')[1].focus();
    $('#filter-input').on('focusout', function () {
      if ( $('.modal').attr('style') != "display: block;"){
        $('input:text')[1].focus();
      }
    })
  }, 500);

  $('#submit-form').on('click', function(){
    setTimeout(function(){
      window.location.href = "<%= orders_path %>";
    }, 250)
  })

    $('input:text').on('itemAdded', function (event) {
        // event.item: contains the item
        var cardFront = $('.' + event.item + '-front');
        var cardBack = $('.' + event.item + '-back');

        if (cardFront.length > 0) {
            cardFront.fadeOut(function(){ cardBack.fadeIn()});
            toastr.success('Znaleziono przedmiot', 'Sukces');
        } else {
            $.get('/ajax?<%= params[:back] ? 'back=true&' : '' %>ean=' + event.item + '&order=' + <%= @order.id %>, function (data) {
                if (data.length > 100) {
                    $('.items-container').append(data)
                    toastr.warning('Znaleziono przedmiot spoza zamówienia', 'Uwaga');
                } else {
                    $($('span[data-role=remove]')[$('span[data-role=remove]').length-1]).trigger('click');
                    toastr.error('Przedmiot nie dostępny', 'Błąd');
                }
            })
        }
        if ($('.card').length == $('.card.is-flipped').length) {
            toastr.success('Wydano cały sprzęt.', 'Sukces');
        }

        // remove removal from tags input
        // $('span[data-role=remove]').hide()

        // refresh counter
        $('.btn-counter').attr('value', 'Wydaj zeskanowany sprzęt (' + $('span[data-role=remove]').length + ')')

        $("a[data-remote]").off();

        $("a[data-remote]").on("ajax:success", function(e){
          toastr.warning('Przekazano do serwisu', 'Sukces');
          console.log(this)
          $(this).parent('div').parent('div').parent('td').parent('tr').css('color', '#dedede');
          $(this).parent('div').html('<span class="label label-danger"><i class="fa fa-fw fa-times" aria-hidden="true"></i> Serwis</span>')
        });

    });

    $('input:text').on('itemRemoved', function (event) {
      // remove from extra items
      $('#' + event.item).remove();

      // remove from main items
      var cardFront = $('.' + event.item + '-front');
      var cardBack = $('.' + event.item + '-back');
      cardBack.fadeOut(function(){ cardFront.fadeIn()});
    });

    

</script>