config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    get 'pdf'
    post 'pdf_raport'
  end
  resources :item_groups
  resources :item_types
  resources :items do
    get 'service'
    post 'add_history'
  end

  # custom routes
  get 'item_barcodes' => 'items#index_barcodes'
  get 'ajax' => 'items#ajax'
  get 'change_status' => 'items#change_status'
  get 'panel' => 'home#scan'
  get 'schedule' => 'home#schedule_pdf'
  get 'orders_panel' => 'orders#panel'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/item_group.rb
class ItemGroup < ApplicationRecord
  has_many :items, dependent: :nullify

  def unavailable?
    i = items.pluck(:status)
    i.include?(ITEM_RESERVED) || i.include?(ITEM_BUSY) || i.include?(ITEM_SERVICE)
  end

end

app/controllers/item_groups_controller.rb
class ItemGroupsController < ApplicationController
  before_action :set_item_group, only: [:show, :edit, :update, :destroy]

  # GET /item_groups
  def index
    @item_groups = ItemGroup.includes(:items => :item_type)
  end

  # GET /item_groups/1
  def show
  end

  # GET /item_groups/new
  def new
    @item_group = ItemGroup.new
  end

  # GET /item_groups/1/edit
  def edit
    redirect_back(fallback_location: @item_group) if @item_group.unavailable?
  end

  # POST /item_groups
  def create
    @item_group = ItemGroup.new(item_group_params)

    if @item_group.save
      redirect_to item_groups_url, notice: 'Item group was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /item_groups/1
  def update
    @item_group.assign_attributes(item_group_params)
    @item_group.item_ids = params['item_group']['item_ids']
    if @item_group.save#update(item_group_params)
      redirect_to item_groups_url, notice: 'Item group was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /item_groups/1
  def destroy
    @item_group.item_ids.clear
    @item_group.save
    @item_group.destroy
    redirect_to item_groups_url, notice: 'Item group was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_group
      @item_group = ItemGroup.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_group_params
      params.require(:item_group).permit(:name, item_ids: {})
    end
end

app/helpers/item_groups_helper.rb
module ItemGroupsHelper
end

app/views/item_groups/_form.html.erb
<%= bootstrap_form_for(@item_group) do |f| %>

  <%= f.text_field :name, label: 'Nazwa' %>

  <%= f.select :item_ids, Item.where(item_group_id: [nil, @item_group.id]).collect {|x| [x.name, x.id]}, {label: 'Sprzęt'}, :multiple => true, class: 'chosen-select' %>

  <div class="actions">
    <%= f.submit 'Zapisz', class: 'btn btn-success' %>
    <%= link_to 'Wróć', item_groups_path, class: 'btn btn-default' %>
    <%= link_to 'Usuń zestaw', item_group, class: 'btn btn-danger', method: :delete, data: { confirm: 'Na pewno chcesz usunąć zestaw? Operacja ta jest nie odwracalna.' } if !@item_group.new_record?%>
  </div>

<% end %>

<script> 
$(document).ready(function(){
  $('.chosen-select').chosen();
});
</script>

app/views/item_groups/edit.html.erb
<div class="page-inner">
  <div class="page-title">
    <h3 class="breadcrumb-header">Edytuj zestaw</h3>
  </div>
  <div id="main-wrapper">
    <div class="row">
      <div class="col-lg-12">
        <%= render 'form', item_group: @item_group %>
      </div>
    </div>
  </div>
</div>

app/views/item_groups/index.html.erb
<div class="page-inner">
  <div class="page-title">
      <h3 class="breadcrumb-header">Zestawy</h3>
      <%= link_to '<i class="fa fa-plus"></i> Dodaj zestaw'.html_safe, new_item_group_path, class: 'btn btn-info'  %>
  </div>
  <div id="main-wrapper">
    <div class="row">
      <div class="col-lg-12">

        <br>
        <div class="form-group">
          <input class="form-control" type="text" onkeyup="filterInput()" placeholder="Filtruj.." id="filter-input">
        </div>
          <table class='responsive table table-sm' id="table">
            <thead class="thead-light">
              <tr>
                <th>Nazwa</th>
                <!-- <th></th> -->
                <th>Sprzęt</th>
              </tr>
            </thead>

            <tbody>
              <% @item_groups.each do |item_group| %>
                <tr>
                  <td>
                    <%= link_to item_group.name, item_group, class: item_group.unavailable? ? 'text-danger' : '' %>
                  </td>
                  <!-- <td>
                    <%= link_to '<i class="fa fa-lg fa-pencil"></i>'.html_safe, edit_item_group_path(item_group), class: (item_group.unavailable? ? 'text-muted' : 'text-warning') unless item_group.unavailable? %>
                    <%= link_to '<i class="fa fa-lg fa-times"></i>'.html_safe, item_group, class: (item_group.unavailable? ? 'text-muted' : 'text-danger'), method: :delete, data: { confirm: 'Are you sure?' } unless item_group.unavailable? %>
                  </td> -->
                  <td>
                    <% item_group.items.each do |q| %>
                      <div class="item-group-item">
                        <%= link_to q.label, q, class: status_to_class(q) %>
                      </div>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>


          </table>
        </div>
      </div>
    </div>
  </div>
<script>
  function filterInput() {
    // Declare variables
    var input, filter, table, tr, td, i, txtValue;
    input = document.getElementById("filter-input");
    filter = input.value.toUpperCase();
    table = document.getElementById("table");
    tr = table.getElementsByTagName("tr");

    // Loop through all table rows, and hide those who don't match the search query
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[0];
      td2 = tr[i].getElementsByTagName("td")[1];
      if (td) {
        txtValue = td.textContent || td.innerText;
        txtValue2 = td2.textContent || td2.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1 || 
          txtValue2.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }
    }
  }
</script>

app/views/item_groups/new.html.erb
<div class="page-inner">
  <div class="page-title">
    <h3 class="breadcrumb-header">Dodaj zestaw</h3>
  </div>
  <div id="main-wrapper">
    <div class="row">
      <div class="col-lg-12">
        <%= render 'form', item_group: @item_group %>
      </div>
    </div>
  </div>
</div>

app/views/item_groups/show.html.erb
<style>
  table tr td {
    padding: 5px;
  }
</style>
<div class="page-inner">
  <div class="page-title">
    <h3 class="breadcrumb-header">Szczegóły zestawu</h3>
  </div>
  <div id="main-wrapper">
    <div class='row'>
      <div class='col col-md-2'>
        <div class='text-secondary text-center' style='font-size: 6em;margin-bottom: -25px'>
          <i class="fa fa-folder-o" aria-hidden="true"></i><br>
        </div>
        <div class='text-secondary text-center' style='font-size: 2em; line-height: 30px;'>
          Zestaw
        </div>
      </div>
      <div class='col col-md-10'>
        <h3>
          <%= @item_group.name %>
        </h3>

        <div class='row'>
          <% @item_group.items.each do |item| %>
            <%= link_to item, class: 'text-secondary' do %>
              <div class='col col-md-2'>
                <table>
                  <tr>
                    <td>
                      <div class='text-secondary text-center' style='font-size: 3em;margin-bottom: -15px'>
                        <%= item.item_type.fa %><br>
                      </div>
                      <div class='text-secondary text-center' style='font-size: 0.8em;line-height: 30px;'>
                        <%= item.item_type.name %>
                      </div>
                    </td>
                    <td>
                      <div>
                        <%= item.name %><br>
                        <%= item.ean %><br>
                        <%= render 'items/item_status', s: item.status if item.status %>
                      </div>
                    </td>
                  </tr>
                </table>
              </div>
            <% end %>
          <% end %>
        </div>

      </div>

    </div>
    <hr>
<%= link_to 'Edytuj', edit_item_group_path(@item_group), class: (@item_group.unavailable? ? 'btn btn-sm btn-warning disabled' : 'btn btn-sm btn-warning') %>