config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    get 'pdf'
    post 'pdf_raport'
  end
  resources :item_groups
  resources :item_types
  resources :items do
    get 'service'
    post 'add_history'
  end

  # custom routes
  get 'item_barcodes' => 'items#index_barcodes'
  get 'ajax' => 'items#ajax'
  get 'change_status' => 'items#change_status'
  get 'panel' => 'home#scan'
  get 'schedule' => 'home#schedule_pdf'
  get 'orders_panel' => 'orders#panel'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/item.rb
class Item < ApplicationRecord
  audited

  validates_uniqueness_of :ean
  validates_uniqueness_of :name
  
  belongs_to :item_type
  has_many :histories
  belongs_to :item_group, optional: true
  has_and_belongs_to_many :orders, through: :orders_items

  def label
    ('<i class="' + item_type.icon + '" ></i> ' + name).html_safe
  end

  def group_name
    if item_group.nil?
      '-'
    else
      item_group.name
    end
  end

  def barcode
    require 'barby/barcode/code_128'
    require 'barby/outputter/cairo_outputter'

    begin
      barcode = Barby::Code128.new(ean)
      outputter = Barby::CairoOutputter.new(barcode)
      outputter.to_svg(height: 12, ydim: 10, margin: 0)
    rescue
      "<span>---</span>"
    end
  end
end

app/models/item_type.rb
class ItemType < ApplicationRecord
  has_many :items, dependent: :delete_all

  def label
    ('<i class="' + icon + '" aria-hidden="true"></i> ' + name).html_safe
  end

  def fa
    ('<i class="' + icon + '" aria-hidden="true"></i>').html_safe
  end

  def f_keys
    if feature_keys
      feature_keys.split(',')
    else
      []
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.includes(:item_type).includes(:item_group)
  end

  # GET /item_barcodes
  def index_barcodes
    @items = Item.all
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  def add_history
    @item = Item.find(params[:item_id])
    if @item.histories.push(History.new(value: params[:history][:value]))
      redirect_to @item, notice: 'Wpis dodany.'
    else
      render :show, alert: 'Coś poszło nie tak.'
    end
  end

  # GET /items/1/ajax
  def ajax
    if params[:back]
      @item = Item.where(ean: params[:ean], status: [ITEM_BUSY, ITEM_SERVICE]).first
      if @item
        item_order = @item.orders.order(:created_at).last
      end
    else
      @item = Item.where(ean: params[:ean], status: [ITEM_ACTIVE, ITEM_RESERVED]).first
      if @item
        @order = Order.find(params[:order])
        if @item.status == ITEM_RESERVED && !@item.orders.include?(@order)
          # przedmiot zarezerwowany w innym zleceniu
          @item = nil
          render layout: false
          return
        end
        item_order = @item.orders.order(:created_at).last
      end
    end
    render layout: false
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    @item.assign_attributes(item_params)

    features = {}
    @item.item_type.f_keys.each_with_index do |k, i|
      features[k] = params[:item][:features][i]
    end
    @item.features = features

    if @item.save
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  def change_status
    ids = params[:ids].split(',')
    if ids.blank?
      render json: { status: 'error', msg: 'Nie wybrano sprzętu.' }
      return
    end

    statuses = Item.find(ids).pluck(:status).uniq
    unless (statuses & [ITEM_RESERVED, ITEM_BUSY, ITEM_SERVICE]).blank?
      render json: { status: 'warning', msg: 'Nie wyporzyczono, nie cały sprzęt jest na stanie.' }
      return
    end

    Item.find(ids).each do |item|
      item.update(status: ITEM_BUSY)
    end
    render json: { status: 'success', msg: 'Wyporzyczono sprzęt.' }

  end

  def service
    @item = Item.find(params[:item_id]) rescue nil

    unless @item
      redirect_to items_url, error: 'Przedmiotu nie odnaleziono.' and return
    end

    if [ITEM_ACTIVE, ITEM_RESERVED].include? @item.status
      @item.update(status: ITEM_SERVICE)
      redirect_to @item, notice: 'Przekazano do serwisu.'
    else
      redirect_to @item, flash: { error: 'Nie można skierować do serwisu. Sprawdź status przedmiotu.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def item_params
    params.require(:item).permit(:name, :item_type_id, :ean, :description)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def audited_item_header v
    case v
    when 'item_type_id'
      'Typ sprzętu'
    when 'item_group_id'
      'Grupa'
    when 'name'
      'Nazwa'
    when 'ean'
      'EAN'
    when 'description'
      'Opis'
    when 'features'
      'Cechy'
    when 'owner'
      'Osoba'
    else
      v.capitalize
    end
  end

  def audited_item_value k, v
    case k
    when 'item_type_id'
      ItemType.find(v).label rescue '-'
    when 'item_group_id'
      ItemGroup.find(v).name rescue '-'
    when 'status'
      case v
      when ITEM_ACTIVE
        '<span class="label label-success"><i class="fa fa-fw fa-check" aria-hidden="true"></i> Na stanie</span>'
      when ITEM_RESERVED
        '<span class="label label-warning"><i class="fa fa-fw fa-exclamation-triangle" aria-hidden="true"></i> Rezerwacja</span>'
      when ITEM_BUSY
        '<span class="label label-primary"><i class="fa fa-circle-o-notch fa-fw"></i> Zajęty</span>'
      when ITEM_SERVICE
        '<span class="label label-danger"><i class="fa fa-fw fa-times" aria-hidden="true"></i> Serwis</span>'
      else 
        '-'
      end 
    when 'features'
      v.map{|k, v| "#{k}: #{v}"}.join(", ")
    when 'owner'
      v.empty? ? '(brak)' : v
    else
      v
    end
  end

  def recent_service_date audits
    audits.select{|q| 
      q.audited_changes.keys.include?("status") && q.audited_changes[:status].is_a?(Array) && q.audited_changes[:status].last == 3
    }.map{|q| q.created_at}.max
  end

end

app/views/items/_form.html.erb
  <%= bootstrap_form_for(@item) do |f| %>
    <% if item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">

      <div class="col-md-6">
        <%= f.text_field :name, label: 'Nazwa' %>
      </div>

      <div class="col-md-6">
        <%= f.text_field :ean, label: 'EAN' %> 
      </div>

    </div>
    <%= f.form_group :item_type_id, label: nil, help: nil do %>
      <div class='row'>
        <% ItemType.all.each do |it| %>
          <div class='col-md-2'>
            <%= f.radio_button :item_type_id, it.id, label: it.label, inline: true %>
          </div>
        <% end %>
      </div>
    <% end %>

    <%= f.text_area :description, label: 'Opis' %>
    <% unless @item.new_record? %>
      <br />
      <h4>Cechy</h4>
      <% @item.item_type.f_keys.each do |k| %>
        <div class='row'>
          <%= f.text_field :features, wrapper: { class: 'col col-md-6' }, name: 'item[features][]', value: @item.features[k], label: k %>
        </div>
      <% end %>
    <% end %>

    <div class="actions">
      <%= f.submit 'Zapisz', class: 'btn btn-success' %>
      <%= link_to 'Wróć', items_path, class: 'btn btn-default' %>
    </div>
  <% end %>

app/views/items/_history.html.erb
<h4>Historia</h4>
<p style="margin-top: -12px;"><small>wpisów: <%= item.audits.count %></small></p>
<div class="profile-timeline" style="margin-top: 10px;">
  <ul class="list-unstyled">
    <li class="timeline-item">
      <div class="panel panel-white">
        <div class="panel-body">
          <div class="timeline-item-post" style="margin-top: -15px;">
            <% item.audits.reverse.each do |a|%>
              <div class="timeline-comment">
                <div class="timeline-comment-header">
                  <p>
                    <%= a.created_at.strftime("%d-%m-%Y %H:%M") %>
                  </p>
                </div>
                <p class="timeline-comment-text">
                  <table>
                    <% a.audited_changes.each do |k, v| %>
                      <tr>
                        <td class='text-right'>
                          <%= audited_item_header(k) %>
                        </td>
                        <td class=''>
                          <% if v.is_a? Array %>
                            <span class='text-warning'>
                              <%= audited_item_value(k, v.first).to_s.html_safe %>
                            </span>
                            ->
                            <span class='text-success'>
                              <%= audited_item_value(k, v.last).to_s.html_safe %>
                            </span>
                          <% else %>
                            <span class='text-success'>
                              <%= audited_item_value(k, v).to_s.html_safe %>
                            </span>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </table>
                </p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </li>
  </ul>
</div>

app/views/items/_item_status.html.erb
<% case s %>
<% when ITEM_ACTIVE %>
  <span class="label label-success"><i class="fa fa-fw fa-check" aria-hidden="true"></i> Na stanie</span>
<% when ITEM_RESERVED %>
  <span class="label label-warning"><i class="fa fa-fw fa-exclamation-triangle" aria-hidden="true"></i> Rezerwacja</span>
<% when ITEM_BUSY %>
  <span class="label label-info"><i class="fa fa-circle-o-notch fa-spin fa-fw"></i> Zajęty</span>
<% when ITEM_SERVICE %>
  <span class="label label-danger"><i class="fa fa-fw fa-times" aria-hidden="true"></i> Serwis</span>
<% else %>
  -
<% end %>

app/views/items/_service_history.html.erb
<h4>Historia serwisowa</h4>
<p style="margin-top: -12px;"><small>wpisów: <%= item.histories.count %></small></p>
<div class="profile-timeline" style="margin-top: 10px;">
  <ul class="list-unstyled">
    <li class="timeline-item">
      <div class="panel panel-white">
        <div class="panel-body">
          <div class="timeline-item-post" style="margin-top: -15px;">
            <div class="timeline-comment">
              <p class="timeline-comment-text">
                <%= bootstrap_form_for(History.new, url: item_add_history_path(item), method: :post) do |f| %>
                  <%= f.text_area :value, label: 'Wpis serwisowy' %>
                  <%= f.submit 'Dodaj wpis', class: 'btn btn-success' %>
                <% end %>
              </p>
            </div>

            <% item.histories.reverse.each do |history| %>
              <div class="timeline-comment">
                <div class="timeline-comment-header">
                  <p>
                    <%= history.created_at.strftime("%d-%m-%Y %H:%M") rescue '---'%>
                  </p>
                </div>
                <p class="timeline-comment-text">
                <table>
                    <tr>
                      <td class='text-right'>
                        Wpis serwisowy:
                      </td>
                      <td class=''>
                        <%= history.value %>
                      </td>
                    </tr>
                </table>
                </p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </li>
  </ul>
</div>

app/views/items/ajax.html.erb
<% if @item %>
  <tr id="<%= @item.ean %>">
    <td>
      <%= link_to @item.name, @item %>
    </td>
    <td>
      <%= link_to @item do %>
        <%= @item.ean %>
      <% end %>
    </td>
    <td>
      <% if @item.item_type %>
        <%= @item.item_type.fa %>
        <%= @item.item_type.name %>
      <% end %>
    </td>
    <td>
      <% if @item.item_group %>
        <%= link_to @item.item_group.name, @item.item_group %>
      <% else %>
        (brak)
      <% end %>
    </td>
    <td class="col-md-2">
      <div>
        <% case @item.status %>
        <% when ITEM_ACTIVE %>
          <span class="label label-success"><i class="fa fa-fw fa-check" aria-hidden="true"></i> Na stanie</span>
        <% when ITEM_RESERVED %>
          <span class="label label-warning"><i class="fa fa-fw fa-exclamation-triangle" aria-hidden="true"></i> Rezerwacja</span>
        <% when ITEM_BUSY %>
          <span class="label label-info"><i class="fa fa-circle-o-notch fa-spin fa-fw"></i> Zajęty</span>
        <% when ITEM_SERVICE %>
          <span class="label label-danger"><i class="fa fa-fw fa-times" aria-hidden="true"></i> Serwis</span>
        <% else %>
          -
        <% end %>
        <%= link_to item_service_path(@item), remote: true, class: 'btn btn-danger btn-xs' do %>
          <i class="fa fa-fw fa-wrench"></i>
          Serwisuj
        <% end %>
      </div>
    </td>
  </tr>
<% end %>

app/views/items/edit.html.erb
<div class="page-inner">
  <div class="page-title">
      <h3 class="breadcrumb-header">Edycja sprzętu</h3>
  </div>
  <div id="main-wrapper">
    <div class="row">
      <div class="col-lg-12">
				<%= render 'form', item: @item %>
			</div>
		</div>
	</div>
</div>

app/views/items/index.html.erb
<div class="page-inner">
  <div class="page-title">
    <h3 class="breadcrumb-header">Sprzęt</h3>
    <%= link_to '<i class="fa fa-plus"></i> Dodaj wpis'.html_safe, new_item_path, class: 'btn btn-info' %>
  </div>
  <div id="main-wrapper">
    <div class="row">
      <div class="col-lg-12">

        <br>
        <div class="form-group">
          <label for="item_name">Nazwa</label>
          <input class="form-control" type="text" onkeyup="filterInput()" placeholder="Filtruj.." id="filter-input">
        </div>
        <table class='responsive table table-sm' id='dttb-items'>
          <thead>
          <th>Nazwa</th>
          <!-- <th></th> -->
          <th>EAN</th>
          <th>Kod kreskowy</th>
          <th>Typ</th>
          <th>Grupa</th>
          <th>Dostępność</th>
          <!-- <th><%= link_to 'Wypożycz zaznaczone'.html_safe, '', class: 'btn btn-default change_status' %></th> -->
          </tr>
          </thead>

          <tbody>
          <% @items.each do |item| %>
            <tr>
              <td>
                <%= link_to item.name, item %>
              </td>
              <!-- <td>
                  <%= link_to '<i class="fa fa-lg fa-pencil"></i>'.html_safe, edit_item_path(item), class: 'text-warning' %>
                  <%= link_to '<i class="fa fa-lg fa-times"></i>'.html_safe, item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %>    
                </td> -->
              <td>
                <%= link_to item do %>
                  <%= item.ean %>
                <% end %>
              </td>
              <td>
                <div class='barcode'>
                  <%= item.barcode.html_safe %>
                </div>
              </td>
              <td>
                <% if item.item_type %>
                  <%= item.item_type.fa %>
                  <%= item.item_type.name %>
                <% end %>
              </td>
              <td>
                <% if item.item_group %>
                  <%= link_to item.item_group.name, item.item_group %>
                <% else %>
                  (brak)
                <% end %>
              </td>
              <td>
                <% case item.status %>
                <% when ITEM_ACTIVE %>
                  <span class="label label-success"><i class="fa fa-fw fa-check" aria-hidden="true"></i> Na stanie</span>
                <% when ITEM_RESERVED %>
                  <span class="label label-warning"><i class="fa fa-fw fa-exclamation-triangle" aria-hidden="true"></i> Rezerwacja</span>
                <% when ITEM_BUSY %>
                  <span class="label label-info"><i class="fa fa-circle-o-notch fa-spin fa-fw"></i> Zajęty</span>
                <% when ITEM_SERVICE %>
                  <span class="label label-danger"><i class="fa fa-fw fa-times" aria-hidden="true"></i> Serwis</span>
                <% else %>
                  -
                <% end %>
              </td>
              <!-- <td>
                  <%= check_box_tag item.id %>
                  
                </td> -->
            </tr>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    $('.change_status').on('click', function (e) {
        e.preventDefault();

        ids = [];
        $('input:checked').each(function () {
            ids.push($(this).attr('id'))
        });

        $.get("<%= change_status_path %>?ids=" + ids.join(','), function (data) {
            $(".result").html(data);
            console.log(data);
            if (data.status == 'success')
                toastr.success(data.msg);
            else if (data.status == 'warning')
                toastr.warning(data.msg);
            else if (data.status == 'error')
                toastr.error(data.msg);
        });

    });

    function filterInput() {
        // Declare variables
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("filter-input");
        filter = input.value.toUpperCase();
        table = document.getElementById("dttb-items");
        tr = table.getElementsByTagName("tr");

        // Loop through all table rows, and hide those who don't match the search query
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            td2 = tr[i].getElementsByTagName("td")[1];
            td3 = tr[i].getElementsByTagName("td")[2];
            td4 = tr[i].getElementsByTagName("td")[3];
            td5 = tr[i].getElementsByTagName("td")[4];
            td6 = tr[i].getElementsByTagName("td")[5];
            if (td) {
                txtValue = td.textContent || td.innerText;
                txtValue2 = td2.textContent || td2.innerText;
                txtValue3 = td3.textContent || td3.innerText;
                txtValue4 = td4.textContent || td4.innerText;
                txtValue5 = td5.textContent || td5.innerText;
                txtValue6 = td6.textContent || td6.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1 ||
                    txtValue2.toUpperCase().indexOf(filter) > -1 ||
                    txtValue3.toUpperCase().indexOf(filter) > -1 ||
                    txtValue4.toUpperCase().indexOf(filter) > -1 ||
                    txtValue5.toUpperCase().indexOf(filter) > -1 ||
                    txtValue6.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }

</script>

app/views/items/index_barcodes.html.erb
<table border=1>
  <tr>
    <% @items.each_with_index do |item, i| %>
      <td style='padding: 15px;' class='text-center'>

        <div class='barcode'>
          <%= item.barcode.html_safe %>
        </div>

        <%= item.name %> |
        <%= item.ean %>

        <% if i % 4 == 3 %>
          </tr><tr>
        <% end %>
        
      </td>
    <% end %>
  </tr>
</table>

app/views/items/item_history.html.erb
<div>
  <% @item.audits.each do |a|%>
    <p>Changes for <%= @item.name %>, <% @item.ean %> at <%= a.created_at %> </p>
    <ul>
      <% a.audited_changes.each do |k, v| %>
        <li>
          <%= k %>: <% if v.is_a? Array %> <%= v.first %> -> <%= v.last %> <% else %> <%= v %> <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/items/new.html.erb
<div class="page-inner">
  <div class="page-title">
    <h3 class="breadcrumb-header">Dodaj sprzęt</h3>
  </div>
  <div id="main-wrapper">
    <div class="row">
      <div class="col-lg-12">
  		  <%= render 'form', item: @item %>
		  </div>
    </div>
	</div>
</div>``

app/views/items/show.html.erb
<style>
  table tr td { padding: 5px; }
</style>

<div class="page-inner">
  <div class="page-title">
    <h3 class="breadcrumb-header">Szczegóły sprzętu <%= @item.name %></h3>
  </div>
  <div id="main-wrapper">
    <div class="row">
      <div class="col-lg-12">

        <div class='row'>

          <div class='col col-md-2'>
            <div class='text-secondary text-center' style='font-size: 6em;margin-bottom: -25px'>
              <i class="<%= @item.item_type.icon %>" aria-hidden="true"></i><br>
            </div>
            <div class='text-secondary text-center' style='font-size: 2em;'>
              <%= @item.item_type.name %>
            </div>
          </div>

          <div class='col col-md-10'>
            <h3> 
              <%= @item.name %>
            </h3>
            
            <table>
              <tr>
                <th class='text-right'>Status:</th>
                <td><%= render 'item_status', s: @item.status %></td>
              </tr>

              <tr>
                <th class='text-right'>EAN:</th>
                <td><%= @item.ean %></td>
              </tr>

              <tr>
                <th class='text-right'>Typ:</th>
                <td><i class="<%= @item.item_type.icon %>" aria-hidden="true"></i> <%= @item.item_type.name %></td>
              </tr>

              <tr>
                <th class='text-right'>Opis:</th>
                <td><%= @item.description %></td>
              </tr>
            </table>

          </div>

        </div>
        <%= link_to 'Edytuj', edit_item_path(@item), class: 'btn btn-warning' %>
        <%= link_to 'Serwisuj', item_service_path(@item), class: 'btn btn-info' %>
        <%= link_to 'Usuń', @item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        <hr>
        <div class="row">
          <div class="col-lg-6">
            <%= render 'history', item: @item %>
          </div>

          <div class="col-lg-6">
            <%= render 'service_history', item: @item %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>